# Первый урок по 2 модулю
## Знакомство с Jupyter Notebook

<h1> Hello <h1/>

In [1]:
text = "Hello, Jupyter!"

print (text)

Hello, Jupyter!


In [5]:
a = 100
a

100

In [6]:
a

100

In [7]:
a = 1000
b = 2000

a
b

2000

In [8]:
a, b

(1000, 2000)

In [9]:
print (a,b)

1000 2000


In [2]:
%pip install numpy

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.8/19.8 MB 3.3 MB/s eta 0:00:0000:0100:01

[notice] A new release of pip available: 22.3.1 -> 23.1.2
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [6]:
# Импортирование библиотеки Numpy
import numpy as np

In [4]:
# Создание массива на базе списка
list_1 = [10, 20, 30, 40]

array_1 = np.array(list_1)
array_1

array([10, 20, 30, 40])

In [5]:
list_2 = [10, 20, 3.14]
np.array(list_2)

array([10.  , 20.  ,  3.14])

In [7]:
# Создание пустого массива
np.empty(5)

array([ 1.  ,  2.75,  6.  , 10.75, 17.  ])

In [8]:
# Создание массива из нулей
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [9]:
# Создание массива из единиц
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

- Одномерный массив (вектор-строка)
- Двумерный массив (вектор-столбец, матрица)

In [10]:
# Одномерный массив

np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
# np.arange(10,20)
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [17]:
# Двумерный массив
# Вектор-столбец
# np.arange(10).reshape((10,))
np.arange(10).reshape((10,1))
# np.arange(10)[:, None]

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [19]:
# Создание матрицы
np.arange(10).reshape((2,5))
# np.arange(10)[:, None].reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

- Типы данных NumPy

In [20]:
arr_1 = np.zeros((3,3))
arr_1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
arr_1.dtype

dtype('float64')

In [23]:
# Конвертация типа данных
arr_1.astype("int")

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [27]:
# arr_2 = arr_1.astype("int")
arr_2 = arr_1.astype("uint8")
arr_2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=uint8)

In [25]:
arr_2.dtype

dtype('int64')