In [1]:
import numpy as np

- Генерация массивов со случайными значениями

In [2]:
# Одномерный массив случайных целых значений

arr_0 = np.random.randint(5, size=10)
arr_0

array([1, 4, 4, 0, 1, 0, 1, 1, 0, 4])

In [3]:
np.random.randint(-10,10, size=10)

array([  6,   6,   3,   4,   2,  -8,   7,   7, -10,   2])

In [4]:
np.random.randint(-100, 100, size=(3,5))

array([[-78, -20, -26,  40, -64],
       [ 49, -89,   6, -80, -15],
       [  4, -54, -88,  43,  23]])

In [7]:
# Двумерный массив случайных значений с плавающей точкой в диапазоне от 0 до 1
np.random.random((3,3))

array([[0.10269544, 0.0073544 , 0.63781736],
       [0.89676978, 0.42698163, 0.86150082],
       [0.88989308, 0.98570743, 0.87633223]])

In [8]:
# Массив случайных чисел с плавающей точкой из нормального (гаусого) распределения

np.random.randn(3,4)

array([[-0.37116081, -1.81539578,  1.31151638, -0.9693013 ],
       [-0.1843138 ,  0.11487901,  0.49241691, -0.05791649],
       [-1.16179127, -0.34494735,  1.06840661, -0.37266678]])

- Атрибуты

In [9]:
arr_0 = np.random.randint(5, size=10)
arr_0

array([3, 3, 0, 4, 0, 4, 3, 1, 4, 1])

In [10]:
# Форма массива
arr_0.shape

(10,)

In [11]:
# Тип данных
arr_0.dtype

dtype('int64')

In [12]:
# Мерность массива
arr_0.ndim

1

In [13]:
# Объем занимаемой памяти (в байтах)
arr_0.nbytes

80

- Методы

In [14]:
# Конвертация типов данных
arr_0.astype("float16")

array([3., 3., 0., 4., 0., 4., 3., 1., 4., 1.], dtype=float16)

In [16]:
arr_1 = np.random.randint(100, size=(3, 5))
arr_1

array([[72, 39, 86, 26, 83],
       [64,  1, 29, 50, 70],
       [27, 69, 49, 64, 26]])

In [18]:
# Транспорирование
# arr_1.transpose()
arr_1.T

array([[72, 64, 27],
       [39,  1, 69],
       [86, 29, 49],
       [26, 50, 64],
       [83, 70, 26]])

- Индексация массивов

In [19]:
arr_2 = np.random.randint(10, size=(3,4))
arr_2

array([[3, 6, 1, 4],
       [7, 1, 1, 5],
       [7, 0, 6, 9]])

In [20]:
#  Прямая индексация
arr_2[1]

array([7, 1, 1, 5])

In [21]:
# Обратная индексация
arr_2[-1]

array([7, 0, 6, 9])

In [23]:
# Синтаксис списков и кортежей
# arr_2[2][3]

# Синтаксис NumPy
arr_2[2,3]

9